#!/usr/bin/env python3
"""Bounded production-loop smoke test for the read-only VS1 GFA patch.

Uses the already verified stock VS1 smoke helper and the GFA patch helper.
The test:
- requires the normal splitter to be running in VS2/P300 baseline;
- stops Party and splitter;
- patches only optolinkvs1.py, vs12_adapter.py, requests_util.py;
- creates a temporary legacy poll_list.py with interleaved F7 and GFA 0x6B reads;
- disables MQTT/TCP write ingress and runs the real splitter in VS1;
- validates fresh MQTT values and journal/MainPID;
- restores runtime source, settings, poll override and services exactly.

No Optolink write command is issued by this helper.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import os
from pathlib import Path
import shutil
import stat
import sys
import tempfile
import time
from typing import Any

VERSION = "1.0.0"
ROOT = Path("/opt/optolink")
SETTINGS = ROOT / "settings_ini.py"
TEMP_POLL = ROOT / "poll_list.py"
SPLITTER = "optolink-splitter.service"
PARTY = "optolink-party-emulator.service"

STOCK_HELPER = Path("/root/wb2a-stock-vs1-smoke.py")
STOCK_SHA256 = "eb94c4eab0e690ac38a53ceaa2389749d2432fb1ed5f49e15a340cf038d9ab35"
PATCH_HELPER = Path("/root/optolink-apply-vs1-gfa-readonly-patch.py")
PATCH_SHA256 = "39880226b471e157b20d2527847c7a7bc2d062abb1f19d9153ee42514253f6ea"

RUNTIME_FILES = ("optolinkvs1.py", "vs12_adapter.py", "requests_util.py")
BASE_BLOBS = {
    "optolinkvs1.py": "cff6b4d8d52ca4ee1f79c310dd9377dba1a18270",
    "vs12_adapter.py": "dfcd97cbe598bb71aafd5c1735e1fb4018b8be68",
    "requests_util.py": "0e2b94547518bde504632579d5d7c4da45e56db7",
}
TEMP_SETTINGS = {
    "vs1protocol": True,
    "mqtt_listen": None,
    "tcpip_port": None,
    "olbreath": 0.15,
}


class SmokeError(RuntimeError):
    pass


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def git_blob(path: Path) -> str:
    data = path.read_bytes()
    return hashlib.sha1(b"blob " + str(len(data)).encode("ascii") + b"\0" + data).hexdigest()


def load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise SmokeError(f"cannot import {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def verify_helpers():
    for path, expected in ((STOCK_HELPER, STOCK_SHA256), (PATCH_HELPER, PATCH_SHA256)):
        if not path.is_file():
            raise SmokeError(f"missing helper: {path}")
        actual = sha256_file(path)
        if actual != expected:
            raise SmokeError(f"helper hash mismatch: {path}: {actual} != {expected}")


def make_poll_source(token: str) -> tuple[str, list[tuple[str, int]]]:
    entries = [
        (f"{token}_f7_ident", 0x00F8, 2, "raw", False),
        (f"{token}_gfa_p80", 0x4050, 1, "gfa:raw", False),
        (f"{token}_f7_dayset", 0x2306, 1, "raw", False),
        (f"{token}_gfa_p06", 0x4006, 1, "gfa:30", False),
        (f"{token}_f7_mode", 0x2323, 1, "raw", False),
        (f"{token}_gfa_p09", 0x4009, 1, "gfa:0.3922", False),
        (f"{token}_f7_dhw", 0x6300, 1, "raw", False),
        (f"{token}_gfa_p87", 0x4057, 1, "gfa:raw", False),
    ]
    lines = [
        "# generated by wb2a-vs1-gfa-poll-smoke.py",
        "poll_interval = 1",
        'poll_groups = {"FAST": 1}',
        "poll_items = [",
    ]
    for name, addr, length, fmt, signed in entries:
        lines.append(f'    ("FAST", {name!r}, 0x{addr:04X}, {length}, {fmt!r}, {signed!r}),')
    lines.append("]")
    lines.append("")
    return "\n".join(lines), [(name, addr) for name, addr, *_ in entries]


def expected_topics(settings: dict[str, Any], items: list[tuple[str, int]]) -> dict[str, str]:
    base = str(settings["mqtt_topic"]).rstrip("/")
    fstr = str(settings["mqtt_fstr"])
    out = {}
    for name, addr in items:
        suffix = fstr.format(dpaddr=addr, dpname=name)
        out[base + "/" + suffix] = name
    return out


def validate_values(seen: dict[str, tuple[str, float]], topics: dict[str, str]) -> list[str]:
    by_name = {name: seen[topic][0] for topic, name in topics.items() if topic in seen}
    failures = []

    if by_name.get(next(n for n in by_name if n.endswith("_f7_ident")), "").lower() != "20c2":
        failures.append("F7 00F8 identity is not 20c2")

    p80_name = next(n for n in topics.values() if n.endswith("_gfa_p80"))
    if by_name.get(p80_name, "").lower() != "20":
        failures.append(f"P80 expected 20, got {by_name.get(p80_name)!r}")

    p06_name = next(n for n in topics.values() if n.endswith("_gfa_p06"))
    try:
        p06 = float(by_name[p06_name])
        if not (0.0 <= p06 <= 6000.0):
            failures.append(f"P06 out of bounded range: {p06}")
    except Exception:
        failures.append(f"P06 not numeric: {by_name.get(p06_name)!r}")

    p09_name = next(n for n in topics.values() if n.endswith("_gfa_p09"))
    try:
        p09 = float(by_name[p09_name])
        if not (0.0 <= p09 <= 100.0):
            failures.append(f"P09 out of bounded range: {p09}")
    except Exception:
        failures.append(f"P09 not numeric: {by_name.get(p09_name)!r}")

    p87_name = next(n for n in topics.values() if n.endswith("_gfa_p87"))
    p87 = by_name.get(p87_name, "").lower()
    if len(p87) != 2 or any(ch not in "0123456789abcdef" for ch in p87) or p87 == "ff":
        failures.append(f"P87 raw invalid/quarantined: {p87!r}")

    return failures


def duration_arg(text: str) -> int:
    try:
        value = int(text)
    except Exception as exc:
        raise argparse.ArgumentTypeError("seconds must be integer") from exc
    if value < 20 or value > 60:
        raise argparse.ArgumentTypeError("seconds must be 20..60")
    return value


def self_test() -> int:
    import unittest

    class Tests(unittest.TestCase):
        def test_poll_source_has_interleaved_transports(self):
            src, items = make_poll_source("x")
            self.assertEqual(len(items), 8)
            self.assertEqual(src.count("gfa:"), 4)
            self.assertIn("0x00F8", src)
            self.assertIn("0x4050", src)

        def test_duration(self):
            self.assertEqual(duration_arg("30"), 30)
            for bad in ("19", "61", "bad"):
                with self.assertRaises(argparse.ArgumentTypeError):
                    duration_arg(bad)

        def test_p80_failure(self):
            topics = {
                "t/a": "x_f7_ident",
                "t/b": "x_gfa_p80",
                "t/c": "x_gfa_p06",
                "t/d": "x_gfa_p09",
                "t/e": "x_gfa_p87",
            }
            seen = {
                "t/a": ("20c2", 0.0), "t/b": ("ff", 0.0), "t/c": ("0", 0.0),
                "t/d": ("0", 0.0), "t/e": ("20", 0.0),
            }
            self.assertTrue(any("P80" in x for x in validate_values(seen, topics)))

        def test_p06_7650_rejected(self):
            topics = {
                "t/a": "x_f7_ident",
                "t/b": "x_gfa_p80",
                "t/c": "x_gfa_p06",
                "t/d": "x_gfa_p09",
                "t/e": "x_gfa_p87",
            }
            seen = {
                "t/a": ("20c2", 0.0), "t/b": ("20", 0.0), "t/c": ("7650", 0.0),
                "t/d": ("0", 0.0), "t/e": ("20", 0.0),
            }
            self.assertTrue(any("P06" in x for x in validate_values(seen, topics)))

    result = unittest.TextTestRunner(verbosity=2).run(
        unittest.defaultTestLoader.loadTestsFromTestCase(Tests)
    )
    if result.wasSuccessful():
        print("VS1_GFA_POLL_SMOKE_TESTS=4/4")
        return 0
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--seconds", type=duration_arg, default=30)
    args = parser.parse_args()

    if args.self_test:
        return self_test()
    if not args.execute:
        print("Use --execute for the live bounded smoke test.")
        return 0
    if os.geteuid() != 0:
        raise SmokeError("--execute requires root")

    verify_helpers()
    stock = load_module(STOCK_HELPER, "wb2a_stock_smoke")
    patcher = load_module(PATCH_HELPER, "wb2a_gfa_patcher")

    settings_now = stock.load_effective_settings()
    if settings_now.get("vs1protocol") is not False:
        raise SmokeError("require production vs1protocol=False before test")
    if settings_now.get("port_vitoconnect") is not None:
        raise SmokeError("require port_vitoconnect=None")
    if TEMP_POLL.exists():
        raise SmokeError("poll_list.py already exists; refusing to overwrite it")

    split_state = stock.systemctl_show(SPLITTER)
    if not stock.unit_running(split_state):
        raise SmokeError("require splitter running before test")
    party_state = stock.systemctl_show(PARTY)
    party_running = stock.unit_running(party_state)

    for rel, expected in BASE_BLOBS.items():
        actual = git_blob(ROOT / rel)
        if actual != expected:
            raise SmokeError(f"{rel} is not base runtime: {actual} != {expected}")

    stamp = time.strftime("%Y%m%d-%H%M%S")
    backup = Path("/root") / f"wb2a-vs1-gfa-poll-smoke-backup-{stamp}-{os.getpid()}"
    backup.mkdir(mode=0o700)
    settings_bytes = SETTINGS.read_bytes()
    settings_stat = SETTINGS.stat()
    (backup / "settings_ini.py").write_bytes(settings_bytes)
    for rel in RUNTIME_FILES:
        shutil.copy2(ROOT / rel, backup / rel)

    token = "gfa_smoke_" + time.strftime("%H%M%S")
    poll_source, poll_items = make_poll_source(token)
    topics = expected_topics(settings_now, poll_items)

    capture = None
    patch_backup = None
    test_start = 0.0
    failures = []

    def log(msg: str):
        print(time.strftime("%Y-%m-%dT%H:%M:%S") + " " + msg, flush=True)

    try:
        if party_running:
            log("Stopping " + PARTY)
            stock.run(["systemctl", "stop", PARTY], timeout=15)
        log("Stopping " + SPLITTER)
        stock.run(["systemctl", "stop", SPLITTER], timeout=15)

        log("Applying temporary read-only GFA runtime patch")
        patch_backup = patcher.apply(ROOT)

        TEMP_POLL.write_text(poll_source, encoding="utf-8")
        os.chown(TEMP_POLL, settings_stat.st_uid, settings_stat.st_gid)
        os.chmod(TEMP_POLL, 0o644)
        log("TEMP_POLL_ITEMS=8 (4 F7 + 4 GFA 6B)")

        source = settings_bytes.decode("utf-8")
        patched_settings = stock.patch_assignments_exact(source, TEMP_SETTINGS)
        stock.atomic_write_like(SETTINGS, patched_settings.encode("utf-8"), settings_stat)
        log("TEMP_SETTINGS=vs1protocol:true,mqtt_listen:none,tcpip_port:none,olbreath:0.15")

        capture = stock.MqttCapture(settings_now, topics, log)
        capture.start()
        capture.clear()
        log("MQTT_EXPECTED_TOPICS=8")

        test_start = time.time()
        log("Starting temporary VS1 splitter")
        stock.run(["systemctl", "start", SPLITTER], timeout=15)
        time.sleep(1.0)
        state0 = stock.systemctl_show(SPLITTER)
        if not stock.unit_running(state0):
            raise SmokeError("temporary splitter failed to run")
        pid0 = state0.get("MainPID")
        log("VS1_MAINPID=" + str(pid0))

        deadline = time.monotonic() + args.seconds
        while time.monotonic() < deadline:
            time.sleep(0.5)
            state = stock.systemctl_show(SPLITTER)
            if not stock.unit_running(state):
                raise SmokeError("temporary splitter stopped during test")
            if state.get("MainPID") != pid0:
                raise SmokeError(f"MainPID changed {pid0} -> {state.get('MainPID')}")

        journal = stock.journal_since(test_start - 0.25)
        hits, flags = stock.analyze_journal(journal)
        log("JOURNAL_VS1_INITIALIZED=" + ("yes" if flags["vs1_initialized"] else "no"))
        log("JOURNAL_MAIN_LOOP=" + ("yes" if flags["main_loop"] else "no"))
        log("JOURNAL_UNEXPECTED_RESTART=" + ("yes" if flags["unexpected_restart"] else "no"))
        ff_count = journal.count("returned FF; quarantined")
        log("GFA_FF_QUARANTINED=" + str(ff_count))

        if not flags["vs1_initialized"] or not flags["main_loop"] or flags["unexpected_restart"]:
            failures.append("journal state failed")
        if hits:
            failures.append("journal error patterns: " + repr(hits))
        if ff_count:
            failures.append(f"{ff_count} GFA FF sample(s) quarantined during bounded test")

        seen = capture.snapshot()
        missing = sorted(set(topics) - set(seen))
        log("MQTT_EXPECTED=8")
        log("MQTT_SEEN=" + str(len(set(topics) & set(seen))))
        log("MQTT_MISSING=" + str(len(missing)))
        if missing:
            failures.append("missing MQTT topics: " + repr(missing))
        else:
            value_failures = validate_values(seen, topics)
            failures.extend(value_failures)
            for topic, name in topics.items():
                log(f"SAMPLE {name}={seen[topic][0]}")

    except Exception as exc:
        failures.append(str(exc))
    finally:
        if capture is not None:
            try:
                capture.stop()
            except Exception as exc:
                failures.append("MQTT stop: " + str(exc))

        try:
            if stock.unit_running(stock.systemctl_show(SPLITTER)):
                log("Stopping temporary splitter")
                stock.run(["systemctl", "stop", SPLITTER], timeout=15)
        except Exception as exc:
            failures.append("stop temporary splitter: " + str(exc))

        try:
            stock.atomic_write_like(SETTINGS, settings_bytes, settings_stat)
            if sha256_file(SETTINGS) != hashlib.sha256(settings_bytes).hexdigest():
                raise SmokeError("settings restore hash mismatch")
            log("SETTINGS_RESTORED=yes")
        except Exception as exc:
            failures.append("settings restore: " + str(exc))

        try:
            if TEMP_POLL.exists():
                TEMP_POLL.unlink()
            for pyc in (ROOT / "__pycache__").glob("poll_list.*.pyc") if (ROOT / "__pycache__").exists() else []:
                pyc.unlink()
            log("TEMP_POLL_REMOVED=yes")
        except Exception as exc:
            failures.append("poll override cleanup: " + str(exc))

        try:
            for rel in RUNTIME_FILES:
                shutil.copy2(backup / rel, ROOT / rel)
                if git_blob(ROOT / rel) != BASE_BLOBS[rel]:
                    raise SmokeError(f"runtime restore mismatch: {rel}")
            log("RUNTIME_RESTORED=base")
        except Exception as exc:
            failures.append("runtime restore: " + str(exc))

        restore_epoch = time.time()
        try:
            stock.run(["systemctl", "start", SPLITTER], timeout=15)
            time.sleep(0.5)
            if not stock.unit_running(stock.systemctl_show(SPLITTER)):
                raise SmokeError("restored splitter not running")
            ok, _ = stock.wait_for_journal_marker(
                "VS2/300 protocol initialized", restore_epoch, timeout_s=10.0
            )
            log("RESTORED_BASELINE_PROTOCOL=" + ("VS2/300" if ok else "NOT_CONFIRMED"))
            if not ok:
                failures.append("VS2/300 restore marker missing")
        except Exception as exc:
            failures.append("splitter restore: " + str(exc))

        if party_running:
            try:
                stock.run(["systemctl", "start", PARTY], timeout=15)
                time.sleep(0.5)
                if not stock.unit_running(stock.systemctl_show(PARTY)):
                    raise SmokeError("party restore failed")
                log("PARTY_RESTORED=yes")
            except Exception as exc:
                failures.append("party restore: " + str(exc))

        if not failures:
            try:
                shutil.rmtree(backup)
                if patch_backup and Path(patch_backup).exists():
                    shutil.rmtree(patch_backup)
                log("BACKUPS_REMOVED=yes")
            except Exception as exc:
                failures.append("backup cleanup: " + str(exc))
        else:
            log("BACKUP_RETAINED=" + str(backup))
            if patch_backup:
                log("PATCH_BACKUP_RETAINED=" + str(patch_backup))

    if failures:
        for failure in failures:
            log("ERROR: " + failure)
        log("RESULT=FAIL")
        return 1

    log("RESULT=PASS")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SmokeError as exc:
        print("ERROR: " + str(exc), file=sys.stderr)
        raise SystemExit(1)
